
api_definitions:
  xls_rack_assignments:
    type: xls
    source_files:
      - /path/to/rack_assignments_1.xlsx
      - /path/to/rack_assignments_2.xlsx
    sheet_name: 0

object_mappings:
  racks:
    source_api: xls_rack_assignments
    destination_api: netbox
    destination_endpoint: dcim.racks
    mapping:
      rack_name: Rack_Name
      site: Site
      position: Position
      device: Device
      tenant: Tenant
      status: Status
