api_definitions:
  # NetBox API Definition
  netbox: 
    type: api
    module: pynetbox
    auth_method: token
    auth_function: api  
    auth_args:
      token: ${NETBOX_API_KEY}
    base_urls:
      - https://netbox.app.clemson.edu

  #Cisco DNA Center API Definition (dnacentersdk)
  dnac: 
    type: api
    module: dnacentersdk
    auth_method: login
    auth_function: DNACenterAPI
    auth_args:
      - name: base_url
        value: base_urls
      - name: username
        value: ${DNAC_AUTH_USER}
      - name: password
        value: ${DNAC_AUTH_PW}
      - name: version
        value: 2.3.3.0
      - name: verify
        value: False

    base_urls:
      - https://cisco-dnac.clemson.edu/

object_mappings:

  devices:
    source_api: dnac
    destination_api: netbox
    destination_endpoint: dcim.devices
    find_function: dcim.devices.filter
    create_function: dcim.devices.create
    update_function: dcim.devices.update
    # Fetch device data from DNAC
    fetch_data_code: |
      def fetch_data(client):
        devices = []
        sites = []
        offset = 1
        limit = 500
        while True:
            response = client.sites.get_site(offset=offset, limit=limit)
            sites.extend(response.response)
            if len(response.response) < limit:
                break
            offset += limit
        if not sites:
            raise ValueError("No sites found in Cisco DNA Center.")
        for site in sites:
            membership = self.client.sites.get_membership(site_id=site.id)
            if not membership or not hasattr(membership, 'device'):
                continue  
            if membership.device is None:
                continue  
            for members in membership.device:
                if not members or not hasattr(members, 'response'):
                    continue  
                for device in members.response:
                    if hasattr(device, 'serialNumber'):
                        device['location'] = site.get('siteNameHierarchy')
                        print(f"found device {device.hostname} in site {site.get('siteNameHierarchy')}")
                        devices.append(device)
        return devices

    mapping:
          
          name:
            source: "hostname"
            transform_function:
              - regex_replace('.clemson.edu.*','')
              - change_case('lower')

          # manufacturer:
          #   source: "vendor"
          #   transform_function:
          #     - regex_replace(' Systems Inc','')
          #     - regex_replace('^$','Cisco')
          #     - change_case('title')
          #     - lookup_object('name', 'dcim.manufacturers.filter', 'dcim.manufacturers.create')

          device_type:
            source: "platformId"
            transform_function: 
              - regex_replace('^C', 'Catalyst ')
              - regex_replace('^WS\-C', 'Catalyst ')
              - regex_replace('^IE\-', 'Catalyst IE')
              - regex_replace('^AIR\-AP', 'Catalyst ')
              - regex_replace('^AIR\-CAP', 'Catalyst ')
              - regex_replace('\-K9$', '')
              - regex_replace('^([^\,]+)\,.+', '\1')    
              - lookup_object('model', 'dcim.device_types.filter', 'dcim.device_types.create')

            included_fields:
              - field: manufacturer
                key: name
              - field: manufacturer
                key: slug
                create_if_missing: true
                transform_function: slugify 

          role:
            source: role
            transform_function: 
              - change_case('title')
              - lookup_object('name', 'dcim.device_roles.filter', 'dcim.device_roles.create')

          platform:
            source: ["softwareType", "softwareVersion"]
            transform_function: 
              - concat(' ')
              - regex_replace('^(\d)', 'IOS \1')    
              - lookup_object('name', 'dcim.platforms.filter', 'dcim.platforms.create')

          serial:
            source: "serialNumber"
            transform_function:
               - regex_replace('^([^\,]+)\,.+', '\1')
               - change_case('upper')

          site:
            source: str:"Clemson Network"
            transform_function:
               - lookup_object('name', 'dcim.sites.filter', 'dcim.sites.create')

          status:
            source: "reachabilityStatus"
            transform_function:
               - regex_replace('Reachable', 'active')
               - regex_replace('Unreachable', 'offline')

          # primary_ip4:
          #   source: "managementIpAddress"
          #   transform_function:
          #      - lookup_object('address', 'ipam.ip_addresses.filter', 'ipam.ip_addresses.create')
