api_definitions:
  # NetBox API Definition
  netbox: 
    type: api
    module: pynetbox
    auth_method: token
    auth_function: api  
    auth_args:
      token: ${NETBOX_API_KEY}
    base_urls:
      - https://netbox.app.clemson.edu

  #Cisco DNA Center API Definition (dnacentersdk)
  dnac: 
    type: api
    module: dnacentersdk
    auth_method: login
    auth_function: DNACenterAPI
    auth_args:
      - name: base_url
        value: base_urls
      - name: username
        value: ${DNAC_AUTH_USER}
      - name: password
        value: ${DNAC_AUTH_PW}
      - name: version
        value: 2.3.3.0
      - name: verify
        value: False

    base_urls:
      - https://cisco-dnac.clemson.edu/

object_mappings:

  devices:
    source_api: dnac
    destination_api: netbox
    destination_endpoint: dcim.devices
    find_function: dcim.devices.filter
    create_function: dcim.devices.create
    update_function: dcim.devices.update
    # Fetch device data from DNAC
    fetch_data_code: |
      def fetch_data(client):
        DEBUG=1
        devices = []
        sites = []
        offset = 1
        limit = 50
        items = 50
        while items == limit:
            response = client.sites.get_site(offset=offset, limit=limit)
            sites.extend(response.response)
            items = len(response.response)
            items = 0
            offset += limit
        if not sites: raise ValueError("No sites found in Cisco DNA Center.")
        if DEBUG == 1: print(f"Found {len(sites)} sites")
        items=0
        for site in sites:
            items += 1
            if DEBUG == 1: print(f"Working on Site# {items}: {site.get('siteNameHierarchy')}")
            membership = client.sites.get_membership(site_id=site.id)
            if not membership or not hasattr(membership, 'device'): continue  
            if membership.device is None: continue  
            for members in membership.device:
                if not members or not hasattr(members, 'response'): continue  
                for device in members.response:
                    if hasattr(device, 'serialNumber'):
                        device['siteNameHierarchy'] = site.get('siteNameHierarchy')
                        if DEBUG == 1: print(f"Found device {device.hostname} in site {site.get('siteNameHierarchy')}")
                        devices.append(device)
        return devices

    mapping:
          
          name:
            source: {{ hostname | replace('.clemson.edu','') | lower }}

          device_type:
            source: {{ platformId
              | regex_replace('^C', 'Catalyst ')
              | regex_replace('^WS\-C', 'Catalyst ')
              | regex_replace('^IE\-', 'Catalyst IE')
              | regex_replace('^AIR\-AP', 'Catalyst ')
              | regex_replace('^AIR\-CAP', 'Catalyst ')
              | regex_replace('\-K9$', '')
              | regex_replace('^([^\,]+)\,.+', '\1') }}

            action: lookup_object('model', 'dcim.device_types.filter', 'dcim.device_types.create')

          role:
            source: {{ role | title }}
            action: lookup_object('name', 'dcim.device_roles.filter', 'dcim.device_roles.create')

          platform:
            source: {{ softwareType | default('IOS',true) | upper }} {{ softwareVersion }}     
            action: lookup_object('name', 'dcim.platforms.filter', 'dcim.platforms.create')

          serial:
            source: {{ serialNumber
               | upper }}

          site:
            source: {{ siteNameHierarchy 
               | slice(4,2) 
               | first 
               | replace_regex('([a-z])([A-Z])', '\1 \2') 
               | title
               | default('Default',true) }}
            action: lookup_object('name', 'dcim.sites.filter', 'dcim.sites.create')
           
          location:
            source: {{ siteNameHierarchy 
               | slice(4,3) 
               | first 
               | replace_regex('([a-z])([A-Z])', '\1 \2') 
               | title
               | default('Default',true) }} 
            action: lookup_object('name', 'dcim.locations.filter', 'dcim.locations.create')
           
          status:
            source: {{ reachabilityStatus
               | regex_replace('Reachable', 'active')
               | regex_replace('Unreachable', 'offline') }}

          # primary_ip4:
          #   source: "managementIpAddress"
          #   transform_function:
          #      - lookup_object('address', 'ipam.ip_addresses.filter', 'ipam.ip_addresses.create')
