object_mappings:
  devices:
    source_api: csv 
    destination_api: netbox 
    destination_endpoint: dcim.devices
    fetch_data_function: read_csv  
    source_mapping:
      file_path: ./sample-data/devices.csv  
      delimiter: ","  
    mapping:
      name:
        source: device_name 
      device_type:
        source: device_type
      serial_number:
        source: serial
      site:
        source: site_name
      status:
        source: status
