api_definitions:
  csv:
    type: csv  # Defines the CSV source type
    source_mapping:
      file_path:
        - ./sample-data/devices.csv
      delimiter: ","

  # NetBox API Definition
  netbox: 
    type: api
    module: pynetbox
    auth_method: token
    auth_function: api  
    auth_params:
      token: 25c89f4320476edf29a6cb24a1d2b085b1fd5264
    base_urls:
      - https://netbox.app.clemson.edu

object_mappings:
  devices:
    source_api: csv
    destination_api: netbox
    destination_endpoint: dcim.devices
    fetch_data_function: read_csv
    find_function: dcim.devices.filter
    create_function: dcim.devices.create
    update_function: dcim.devices.update
    mapping:
      name:
        source: device_name
      device_type:
        source: device_type
        transform_function: lookup_object('model', 'dcim.device_types.objects.filter', 'dcim.device_types.create')  # Lookup or create device_type
      serial_number:
        source: serial
      site:
        source: site_name
        transform_function: lookup_object('name', 'dcim.sites.objects.filter', 'dcim.sites.create')  # Lookup or create site
      status:
        source: status