api_definitions:
   # Destination API using pynetbox for NetBox
  netbox:
    type: api
    module: pynetbox
    auth_method: token
    auth_function: api
    auth_args:
      token: ${NETBOX_API_KEY}
    base_urls:
      - https://netbox.app.clemson.edu

  iaw:  
    type: api-swagger
    module: bravado.client
    auth_method: login
    json_url: /docs/swagger.json  
    auth_args:
      login_endpoint: /login
      token_key: token
      username: ${IAW_USERNAME}
      password: ${IAW_PASSWORD}
    base_urls:
      - https://iaw.dev.clemson.edu:8443/api

# Object Mappings Configuration
object_mappings:

  slas:
    source_api: iaw
    destination_api: netbox
    destination_endpoint: plugins.netboxservicemgmt.slas
    find_function: plugins.netboxservicemgmt.slas.filter
    create_function: plugins.netboxservicemgmt.slas.create
    update_function: plugins.netboxservicemgmt.slas.update
    fetch_data_code: |
      def fetch_data(api_client):
            response = api_client.session.request(method="GET",url="https://iaw.dev.clemson.edu:8443/api/slas")
            response.raise_for_status()
            return response.json()

    # {'_id': '666b271cec496524844ff19d', 'agreementNumber': '2026', 'dataRiskCategory': None, 
    # 'status': None, 'agreementName': 'SLA 2026 - Backup Infrastructure', 'servicesProvided': [],
    # 'customerDepartments': ['ISO'], 'ccitDepartments': [], 'customerPointsofContact': ['Jason Davis'], 
    # 'customerBusinessManagers': ['Matt Garrett'], 'dataSummary': None}

    # Mapping Configuration
    mapping:

      name:
        source: {{ agreementName | regex_replace('[\ ]*$','') | replace(' - ','') }}
     
      data_classification:
        source: {{ dataRiskCategory 
          | default("public", true)
          | regex_replace('([^#]+)\#.+$','\\1') 
          | replace(';','') 
          | replace('N/A','public')
          | regex_replace('.*nternal.*$','internal_use')
          | regex_replace('.*ublic.*$','public')
          | regex_replace('.*onfidential.*$','confidential')
          | regex_replace('.*estricted.*$','restricted') }}

      business_owner_tenant:
        source: {{ customerDepartments[0] }}
        action: lookup_object('name', 'tenancy.tenants.filter', 'tenancy.tenants.create')

      business_owner_contact:
        source: {{ customerBusinessManagers[0] 
          | regex_replace('([^#]+)\#.+$','\\1') 
          | replace(';','') }}
        action: lookup_object('name', 'tenancy.contacts.filter', 'tenancy.contacts.create')

      description:
        source: {{ agreementName }} {{ dataSummary | string }}

      technical_contact:
        source: "Unknown"
        action: lookup_object('name', 'tenancy.contacts.filter', 'tenancy.contacts.create')

      slo: 
        source: "Deferrable"
        action: lookup_object('name', 'plugins.netboxservicemgmt.slos.filter', 'plugins.netboxservicemgmt.slos.create')


      

      