# vmware_to_netbox_vms.yaml
include: api_definitions.yaml

object_mappings:
  virtual_machines:
    source_api: *vmware_api
    destination_api: *netbox_api
    destination_endpoint: virtualization.virtual_machines
    fetch_data_function: content.viewManager.CreateContainerView  # Custom VMware function to retrieve VMs
    mapping:
      name: name
      status: runtime.powerState
      cluster: resourcePool.name
      host: runtime.host.name
      cpu_count: config.hardware.numCPU
      memory_mb: config.hardware.memoryMB
      ip_address: guest.ipAddress
