api_definitions:
  # NetBox API Definition
  netbox: 
    type: api
    module: pynetbox

    auth_method: token
    auth_function: api  
    auth_args:
      token: ${NETBOX_API_KEY}
    
    base_urls:
      - https://netbox.app.clemson.edu

  # VMware API Definition (pyvmomi)
  vmware: 
    type: api
    module: pyVim

    auth_method: login
    auth_function: connect.SmartConnect
    auth_args:
      - name: host
        value: base_urls
      - name: user
        value: ${VMWARE_AUTH_USER}
      - name: pwd
        value: ${VMWARE_AUTH_PW}
      - name: sslContext
        value: ignore

    base_urls:
      - cu-vcenter.clemson.edu
      - poole-vcenter.clemson.edu
      - cudr-vcenter.clemson.edu
      - vdi-vcenter.clemson.edu

object_mappings:

  hosts:
    source_api: vmware
    destination_api: netbox
    destination_endpoint: dcim.devices
    find_function: dcim.devices.filter
    create_function: dcim.devices.create
    update_function: dcim.devices.update

    imports:
      - pyVmomi.vim
    
    fetch_data_code: |
      def fetch_data(api_client):
          content = api_client.RetrieveContent()
          hosts = content.viewManager.CreateContainerView(content.rootFolder, [vim.HostSystem], True).view
          return hosts

    mapping:
    
      name:
        source: {{ name | replace('.clemson.edu', '') }}
  
      tenant:
        source: {{ name | replace_map('config/clemson/host_tenant_map.txt') }}
        action: lookup_object('name', 'tenancy.tenants.filter', 'tenancy.tenants.create')

      cluster:
        source: {{ parent.name }}
        action: lookup_object('name', 'virtualization.clusters.filter', 'virtualization.clusters.create')

      role: 
        source: Hypervisor Host
        action: lookup_object('name', 'dcim.device_roles.filter', 'dcim.device_roles.create')

      site:
        source: {{ parent.name 
            | regex_replace('(?i)^CU-.+','Clemson Information Technology Center') 
            | regex_replace('(?i)^CUDR-.+|^DR-.+','University of California San Diego') 
            | regex_replace('(?i)^Poole-.+','Poole') 
            | regex_replace('(?i)^Proto-.+','Clemson Information Technology Center') }}
        action: lookup_object('name', 'dcim.sites.filter', 'dcim.sites.create')

      device_type:
        source: {{ hardware.systemInfo.model }}
        action: lookup_object('model', 'dcim.device_types.filter', 'dcim.device_types.create') # need to add aditional info option here

      status:
        source: {{ runtime.connectionState 
            | replace('connected', 'active') 
            | replace('disconnected', 'offline') }}

      serial:
        source: {{ summary.hardware.otherIdentifyingInfo | extract_item('identifierValue', 'SerialNumberTag') }}

      platform:
        source: {{ config.product.name }} {{ config.product.version }}
        action: lookup_object('name', 'dcim.platforms.filter', 'dcim.platforms.create')

  virtual_machines:
    source_api: vmware
    destination_api: netbox
    destination_endpoint: virtualization.virtual_machines
    find_function: virtualization.virtual_machines.filter
    create_function: virtualization.virtual_machines.create
    update_function: virtualization.virtual_machines.update
    imports:
      - pyVmomi.vim
    fetch_data_code: |
      def fetch_data(api_client):
          content = api_client.RetrieveContent()
          vms = content.viewManager.CreateContainerView(content.rootFolder, [vim.VirtualMachine], True).view                  
          return vms

    mapping:

      name:
        source: {{ config.name | replace('.clemson.edu', '') }}

      status:
        source: {{ runtime.powerState 
            | replace('poweredOn', 'active') 
            | replace('poweredOff', 'offline') }}

      cluster:
        source: {{ runtime.host.parent.name }}
        action: lookup_object('name', 'virtualization.clusters.filter', 'virtualization.clusters.create')

      device:
        source: {{ runtime.host.name | replace('.clemson.edu', '') }}
        action: lookup_object('name', 'dcim.devices.filter', 'dcim.devices.create')

      tenant:
        source: {{ config.name | replace_map('config/clemson/vm_tenant_map.txt') }}
        action: lookup_object('name', 'tenancy.tenants.filter', 'tenancy.tenants.create')

      vcpus:
        source: {{ config.hardware.numCPU | float }}

      memory:
        source: {{ config.hardware.memoryMB }}

      platform:
        source: {{ guest.guestFullName }}
        action: lookup_object('name', 'dcim.platforms.filter', 'dcim.platforms.create')

      serial:
        source: {{ config.uuid }}

      site:
        source: {{ runtime.host.parent.name 
            | regex_replace('(?i)^CU-.+','Clemson Information Technology Center') 
            | regex_replace('(?i)^CUDR-.+|^DR-.+','University of California San Diego') 
            | regex_replace('(?i)^Poole-.+','Poole') 
            | regex_replace('(?i)^Proto-.+','Clemson Information Technology Center') }}
        action: lookup_object('name', 'dcim.sites.filter', 'dcim.sites.create') 