api_definitions:
  # NetBox API Definition
  netbox: 
    type: api
    module: pynetbox
    auth_method: token
    auth_function: api  
    auth_params:
      token: 25c89f4320476edf29a6cb24a1d2b085b1fd5264
    base_urls:
      - https://netbox.app.clemson.edu

  # VMware API Definition (pyvmomi)
  vmware: 
    type: api
    module: pyVim
    auth_method: login
    auth_function: connect.SmartConnect
    auth_params:
      username: esacollector
      password: Upward-Floral4-Avid
      sslContext: ignore
    auth_args:
      - host
      - username
      - password
      - sslContext
    base_urls:
      - cu-vcenter.clemson.edu
      - poole-vcenter.clemson.edu
      - cudr-vcenter.clemson.edu
      - proto-vcenter.clemson.edu
      - vdi-vcenter.clemson.edu

object_mappings:
  virtual_machines:
    source_api: vmware
    destination_api: netbox
    # Source API (VMware) CRUD functions
    fetch_data_function: content.viewManager.CreateContainerView  # For VMware to read VMs
    find_function: content.viewManager.CreateContainerView  # For VMware to "find" VMs
    params:
      object_type: vim.VirtualMachine
      view_type: True
    # Destination API (NetBox) CRUD functions
    create_function: dcim.devices.create  # Create virtual machines as devices in NetBox
    update_function: dcim.devices.update  # Update virtual machines in NetBox
    destination_endpoint: dcim.devices
    mapping:
      name:
        source: name
      status:
        source: runtime.powerState
      cluster:
        source: runtime.host.parent.name
      device:
        source: runtime.host.name
      platform:
        source: guest.guestFullName  
      vcpus:
        source: config.hardware.numCPU
      memory:
        source: config.hardware.memoryMB
      disk:
        source: summary.storage.committed  
      description:
        source: config.annotation
      serial:
        source: customAttributes["serial_number"]  
      comments:
        source: config.annotation
      tags:
        source: customAttributes["tags"]  
